PoncaCmsBundle_homepage:
    pattern:  /cms/hello/{name}
    defaults: { _controller: PoncaCmsBundle:Default:index }
    
cms_add_user:
    pattern:  /{_locale}/cms/add-user
    defaults: { _controller: PoncaCmsBundle:User:addUser }
    requirements:
        _locale: en|fr|de
