parameters:
#    ponca_cms.example.class: Ponca\CmsBundle\Example

services:
#    ponca_cms.example:
#        class: %ponca_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
