Ponca\CmsBundle\Entity\User:
  properties:
    username:
                - MinLength: { limit:4, message:"username.MinLength" }
    email:
                - NotBlank: ~
                - Email: { message:"email.Email", checkMX:true }
    password:
                - Regex: { pattern: "/(\d[a-zA-Z])|([a-zA-Z]\d)/", match: "true", message: "password.Regex" }
                - MinLength: { limit:7, message:"password.MinLength" }
    first_name:
                - MaxLength: { limit:50, message:"first_name.MaxLength" }
                - NotBlank: { message:"" }
    last_name:
                - MaxLength: { limit:50, message:"" }
                - NotBlank: { message:"last_name.NotBlank" }
    group:
                - NotBlank: { message:"group.NotBlank" }
  getters:
    passwordValid:
                - "True": { message:"getters.passwordValid" }
  constraints:
                - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields:email, message:"constraints.unique.email" }
                - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields:username, message:"constraints.unique.username" }