<?php

namespace Ponca\CmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
    public function getGroupArray()
    {
        $r = $this->_em->createQuery(' SELECT g.id FROM Ponca\CmsBundle\Entity\Groups g  ')
                ->getResult();
        var_dump($r);
        return array(3,4);
    }
}