parameters:
#    ponca_admin.example.class: Ponca\AdminBundle\Example

services:
#    ponca_admin.example:
#        class: %ponca_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
