parameters:
#    ponca_security.example.class: Ponca\SecurityBundle\Example

services:
#    ponca_security.example:
#        class: %ponca_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
